name: learn_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - img/
  uses-material-design: true

font:
  - family: Poppins
    fonts:
      - assets: assets/fonts/Poppins-Regular.ttf
      - assets: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - assets: assets/fonts/Poppins-Bold.ttf
        weight: 900